server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/testing_system"
    username: root
    password: cao271102
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
