server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/testing_system"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true

